### ISSUE TITLE
Remove NSD Nesstar endpoint details

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#601]
For some reason, following is still in harvester config file, and should be removed:

```
 - url: https://oai-pmh.nsd.no/oai-pmh/
      code: NSD # Use original code
      name: "Sikt - Norwegian Agency for Shared Services in Education and Research"
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: oai_ddi
          ddiVersion: NESSTAR
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-1.2.2/latest/profile.xml
```

See https://github.com/cessda/cessda.cdc.aggregator.deploy/blob/main/charts/harvester/config/config.yaml
